// Code generated by the English-conversion migration tooling. DO NOT EDIT.
//
// These maps freeze the SHA-256 (hex) of every built-in prompt body and tool
// description/schema that ARTEX shipped as a code default between the initial
// commit and the pre-conversion release (160fe13), recovered from git history.
//
// The English-conversion migrations (server/orchestration.go, server/finding_workflow.go)
// use them to upgrade ONLY rows in an existing database that still hold one of these
// historical Chinese defaults: a row whose current value hashes to a listed digest is
// reset to the new English default; any other value is an operator customization and is
// left untouched. Fresh installs seed English directly and never match here.
//
// Hashing convention (identical at generation time and at runtime):
//   prompt body   : sha256(template_text bytes)
//   tool desc     : sha256(description bytes)
//   tool schema   : sha256(json.Marshal(json.Unmarshal(schema))) — Go canonical form
//     (map keys sorted, HTML-escaped), so a jsonb column round-trips to the same bytes.

package agent

// LegacyPromptSHA256 maps an agent/body key to the set of historical default-body digests.
// Keys: goals, planner, mainagent, worker, auto, pentest, reporter, retester, and
// "_assistant" for DefaultAssistantPrompt.
var LegacyPromptSHA256 = map[string]map[string]struct{}{
	"_assistant": {
		"a179c990bff1ab4e0a6f326945a1c44036ef4c8a54c7c5b635965f6cefdc9f0a": {},
	},
	"auto": {
		"b2a71b82243607337b19f0642317fed88c144d536412d80eaaf90807f2905a1d": {},
	},
	"goals": {
		"72a7a0159443b41dde29dfba8a3de6a2c8a15b273935495a7b88561fa708aa68": {},
		"9c51639015a0a648d08b52d0fa46b32eb432bd0eb4231d75b0ed5bf76ee235ca": {},
	},
	"mainagent": {
		"12bb69ee0886c4fb9beb936d882021a91104860f1da69a5e3eda3d9e345cd399": {},
		"33a2934883fefbf9b41a674921c77027e6d6c9e8f867d150e5f87811f9c9c1df": {},
		"4938dfffee46bf983aa9291e149159eb273999056188b74f666a2173926f9074": {},
		"a1d251781a6b411e68134ca03d4ad4596a21d221152562d2b6d067e7d27aebff": {},
	},
	"pentest": {
		"7c1664f8061295ea70a4dc5977d98c599844ef8fcfedf0e501f8edc7afa35326": {},
		"a54bd5713b1c121d0f2ff3a72e0304820b1368c4b4b8159d5d651895663ac652": {},
	},
	"planner": {
		"01497d1bffc54d5cb041bfe89dd0c0d314a0a6b0e311b1ee2f1bdc18121e4f51": {},
		"14e163f4a44da9fee20a214048a607adc3659b2025275569eb512532ca8c15d5": {},
		"18e7de64cf5e6528b9b852306f12ef73089efd574bb0984e34f49133c141f61c": {},
		"1ca382cd6c964e948af8560f5cbad5f78fa9f4b36031ea46d91eddfc5054ecfe": {},
		"3c0c2b90eee4a1a559efc750c7551e9882bd98caa531f90c0f0a51398483701d": {},
		"49ac9eeaf59f29e31d5ec52d2b0fb977c157e9279b28657629c2a4d1db7e80b4": {},
		"5736b2fd9d264494ee5a0d0eac8d9440e7b85b0a0e3874d84eea48851dcedcf8": {},
		"6c3c694a0c9e21aa6d4b5fffbe1d07affa395c3173f82f2e3decb4c9eca1c91e": {},
		"78bf73294e7d5ad5d2d6b7abaf91213de9fb663b29d2cb602028c7940c279ab6": {},
		"82672b54620846e389d6cf6c63d79ebb294a7ceea52d8a479424621825d0f84c": {},
		"87e60f746a60695bb4fcf00a90fba19a6c5b58a1050168b4a72e2a0d9de1671b": {},
		"e0e2b7b9ff43a8673404b4eacb77ab4e76780589dcd0fb6d6744602334aea17a": {},
	},
	"reporter": {
		"3743a8c374b45a9b24390457ecdbd50465693912a4e0b3c77107056bda5b389b": {},
		"86ad261f9773aec97a8ea1c7040f5efcf5142da53ef1ff49bf1cfd1d227c10cc": {},
		"8ba98208f6c5f2ccb103c88ef13239c4264733400c0e3dfec96d3a3572d78d39": {},
	},
	"retester": {
		"d08326aa9fbd9a1367e716cf7ef46533e9096e9a56493f77d364efbf696f7fe0": {},
	},
	"worker": {
		"261914723f71ca5123e2c310d42a3f34ac8594b32b6d479003c373f282fa83f9": {},
		"40323de406696f782132bf675c2aed17e7a363d3436a326b5dcdc2ef6cbcd6d5": {},
		"48dcd8a04e204d29acddffde6e6213e0f35b369852f8e8233fff5cde96fecc89": {},
		"6450be9f636f580a8737faf6d1f59e137abfd60f8bad35a86ed2f9b379ea4883": {},
		"64cd6524f2f6cabd55b5fcd95612d4db1a340200738c7f83ae768874273728ce": {},
		"7f13bf6d9f3586663a99b45fa8200dd9e25258f73cae5f13c876fdee2f2dbbda": {},
		"80fbb1c610dd57e266c20b9145793339eee540b809f6db8f5336261b45879f08": {},
		"9f40b972a3383c6299fc39889a165414f4960633f8e160e4432ed28558c3ca94": {},
		"b3a50039c00da19800858c58bdbb2ed540fa41a10ee19339b7a34ef521ebdca3": {},
		"b43639b21c6ab4e32bb48ecdcfe09e43c7dde4554d262c36c3256b3064372590": {},
		"c3fe3015fb22020c5afbebafcdd100e4fa4ec307319ecc6fd119003be4579b3c": {},
		"d69f9f3c9375b64640b95d14e84816ae4d80227c9faf74d936c6073205dbab5a": {},
		"de84975cbf8edf9665a0d77b39f7be32dfd75dbb119c516ae4af040af2bcccf2": {},
	},
}

// LegacyToolDescSHA256 maps a tool key to the set of historical default-description digests.
var LegacyToolDescSHA256 = map[string]map[string]struct{}{
	"add_company_scope": {
		"929edb45f9635e2e6dd8b00947f2e793263687d66f04f1026ad840464ab0f4eb": {},
		"c460db4b5834fb3c22d27937a2b87902cd9eaf4246e53e7e44a4081c5d6243f0": {},
	},
	"add_hint": {
		"629c6494669d5d5b53b951c70c949833dc1a885e91c85469caa6a9527b9ca61e": {},
	},
	"add_intent": {
		"6754abb7254a6a7ec1cf980f00a768d384d473f84d4c90b1e0446963c0a92767": {},
	},
	"add_task_hint": {
		"4eb1f206d86556f2ccc0a394e5058250a602848a109f217cbd00bd3338b72b7e": {},
	},
	"add_task_scope": {
		"23caa9d2e944fac4bd7f329bd5de45344a0633ed9f554759c4be753e5c9cc9a3": {},
		"599b4199b34e799f750505ac14fcc69239015b6fdf045fa636c1275ea879ad51": {},
		"cfcd2e031d0be92c28f3181d9424da8680a97cc7f476592522a2a2a8d57cf6f5": {},
	},
	"bind_finding_traffic": {
		"e3ca4e11bf4064efe57ae573a90c73d7e9e8abf5185ae0c108c1984ae4d879af": {},
	},
	"create_custom_tool": {
		"7bfdeabe156fc42becdab03079dab0f7d4d4aead08b0f782f537533121485a28": {},
	},
	"create_mcp": {
		"4ebe76a21a79ff3e549cb58b5db0a90f2b5151fa8195342b1549b79e77bde4b8": {},
		"e71f9d4f5647c8c57d7c0fbe1b86795060e3c31c76fd1d58122061d907b52595": {},
	},
	"create_skill": {
		"40a5e60ab56cebb9f574dc9fb3bb6f2b418c8d8baa452ff441fbf32c1aa82d2e": {},
	},
	"delete_assets_by_host": {
		"194b747997ca61c2b7a6929f61f7642dcc7e2ca24fb37c279fe6d6297ef0a1f0": {},
	},
	"expand_digest": {
		"e0807f8e20e25f3f682a51c688160942e568ac80ca0d16819e7361a9abe68fb1": {},
	},
	"expand_index": {
		"949a12fa7ca013190604489595528c7c1eb625789d64b102b66656dd780f3e66": {},
	},
	"get_finding_retest_context": {
		"c7d224d35a8f484dab0bf72adea727236364b11f7cafe1674f60d81c7985d876": {},
	},
	"get_finding_traffic": {
		"9fbbf5633682ea7d6260cbbfcf20ffd0bf073d659123c8615cc79e753f38afd6": {},
	},
	"get_task_graph": {
		"3f2787299dbfa6bb755a7653cb3cab0c00dece049f4c9a4203ebb105dff80ab8": {},
	},
	"get_task_node_detail": {
		"a0dce2524d6ebc8dc5f94765419d398dd820811a1440169a6f406914a0c2804f": {},
	},
	"get_task_worker_trace": {
		"5c5e3a70e3c8f650b094fcf1296b53de4f7f1763574b68a9142787b2adb77c28": {},
	},
	"get_worker_output": {
		"0d2e86f65d8261efdf3bed1e6d7ad907ed610f4a9002b0514720aaf46f2af4f9": {},
		"41e1f876b4a7cc7ec2e781e73ad9870f974d18de333c3a79d3070e4d2415b8d5": {},
		"f25ffdc9580a39cb8f6aca6c3bde7860934b73b579157533e97ee85ee271f21e": {},
	},
	"get_worker_trace": {
		"5931721f9a063a608b1ad5d72c2ca48b0bd763d607769c4d2161f074c23835ec": {},
		"6b411ef2e24ec311e8c6468088dd1716fb30dbc347195dfe7ff3a725dae1b7e4": {},
		"9540d641cfeb71cada0ee71142b555f56b35c438fa6b1e8be5bafd7f684fa16b": {},
	},
	"goal_met": {
		"cba19394662c07ae525bcf3e21ead34b671a3e391c4e2a020518d4b096a0ac00": {},
	},
	"graph_overview": {
		"541280dbe0192fe121e79d956d9bc41553fa2b317a344cf635ee602aa196ada3": {},
	},
	"insert_assets": {
		"2d45b0171919b70cf00307eb8d521d03a19bc7f3702e2eaca238a83a18e0490a": {},
		"c377ce43215f3b6b573b21e301b27180e62a0cc2a480f7b41d54f61692167dbd": {},
		"ee9925a381d61b13efe9bf0412d199b29b8d48d8109e53b4398dabe2b5edd8f0": {},
	},
	"kill_work": {
		"34036c67e6fa85c1abe66fb5983e390c97acc525b499d6cad20e907877002db9": {},
	},
	"list_assets": {
		"1fd9bccbe24fe0729be7965ab7b43c849661148583675860a7e430e81880cbf2": {},
		"cf302317a50c3f326e7eaefcd0d7f038bac04424d84cf3deeeb602198aa11aff": {},
		"de9dfe208431720be5e727ababa612ad4b2aaf095158360395313b03d043971b": {},
	},
	"list_companies": {
		"100d9924f89e3c50313af8296dafbc16d802733995f32f09cb24709276d2d9a3": {},
	},
	"list_facts": {
		"367be32e153ea77e11ab5d4fdc25b8e2a1a7b733cc8e4bbe20df592c322283e0": {},
		"36f582152ec10368d86a5c35962c8bc4899a201eeb58720e9baef7b0a5aa7b22": {},
		"ee05de7b9f803b44c3c7d74a7f08b4f1fc044a5023828af88214179dbd5c4cc3": {},
	},
	"list_findings": {
		"1e25104858ba614987dee500ff60d67e1fe837910f38ea750d9e2d2e8312bc15": {},
		"a7d3b077708ce49738a2dfcf6b035d509351d885c4fa0ece49aa28d41b90ab7d": {},
	},
	"list_goals": {
		"8badb45c95ec41fd8208f127cf91db19072b586ce25f82893abe5f320aedd433": {},
	},
	"list_llm_profiles": {
		"e4c1aac1216302ab483281f660ae6d528f6aa69fb76605d93fa8b27083aa98ef": {},
	},
	"list_task_findings": {
		"989043941aa39a3eff03f1f9d8088c392301a16dfe113d465301f08f7ac55ac0": {},
	},
	"list_task_worker_traces": {
		"db57bc2c72a4b4e53a9b625fd1158b117521c4104f7d4a7c244b299fb7f15c04": {},
	},
	"list_tasks": {
		"3d5515eb6136cead1b9dd4d3c11368051794ddc9a98c0012d883c7d9f59ac8c3": {},
	},
	"list_untested_assets": {
		"6511ef688f09121f8368d7fefe1bc5605c46d6f16eaab1281bac9d2bc9dec15e": {},
		"751b0466c5ae59415d9c4a375ea4fc271f7b558f08342c8616d2579b3ee8e0d5": {},
	},
	"list_worker_traces": {
		"06ff67297c6a3e3b76fafb270f0043b15a9be01434654662b257c7f63a004bd6": {},
		"9d48b6b9f04b9fe3c2742b34c5b815d4ef4dd50764ca40e28cca4f8ec4065e58": {},
	},
	"node_detail": {
		"15b983a6465d518528df5f0042ca1fbfde7d6f6a7e9a8072656c34b982426417": {},
		"ecb7fd45ccd24f48ec9b26943976ca5360a463539a8519201b53543437c28d54": {},
	},
	"pause_task": {
		"d37d81dbb74321da470ca15e9b2cc6a04f85538f4b1611ef7e05f7f2e11bf6b1": {},
	},
	"prove_goal": {
		"8a40e6de058ad1d43cb9a666b045beeb868f8ad0a04320e76edba6d80fbfad66": {},
	},
	"record_fact": {
		"8b9446c8c11a2cd45f6f5c45bb541a732c399415a718b44b69479e4619078593": {},
		"bb14c4e45b790c7c46fded673d42a62b0c73b011ae143ebdfa99bee99c2d2a85": {},
	},
	"record_finding_retest_result": {
		"15bf1adec32a2b40e515263b5e8ab882b1328669687138dbbcd6cf74d606623f": {},
	},
	"report_finding": {
		"25346d67cac71463c24cdcb2ab8a53408fd077b8b1ebde27fdefd4fa4f7001d5": {},
		"8b50e8f4a77bca6996f78832a1825753ec4d1ef3e4cde46212b1bacee87364cb": {},
		"91675222f3d26a6fd171f6a7c1693c735d9985a7f93d16dcb77610f550d9655d": {},
		"ad2550b01c53a6d1b2674a083cbc03d3032c4a084d8e84995de90f73e63e2d07": {},
	},
	"search_all_worker_traces": {
		"a5198e6bdabe3c86b660a542fe30464ce6846cb522f29312f687ae84a340a0ac": {},
		"a84ee8e52ac9c51df1ed8ec8efd040596c05ace5d59282cfae065c5beba3d8b1": {},
	},
	"search_task_worker_traces": {
		"3a52371e00c54c2287ecdc0cd824faed79e4e409281d2b7a991b7fb619efcb34": {},
	},
	"set_constraints": {
		"46a72ba15f4381fd8c8e2835ca5dee1c3054de81dde1209b5f913f5f8e68a41d": {},
	},
	"set_goals": {
		"0115b98eabff22aea4710fe36255915c9de3b48cd451111da3074118ae83d1dd": {},
	},
	"spawn_task": {
		"d79dc8da3dbfe456ec7ca051ad6751ff8dbf3e2a4db00e0bd26bdbc2631471a6": {},
	},
	"steer_work": {
		"a7a86be80c94c7e3525493136124939428413a3311b5283afa66256da6b5e135": {},
	},
	"traffic_blob": {
		"315f23469723e3c655c74e77f59e87608d750aebc2dce3b14619b24e1a3953c2": {},
	},
	"traffic_get": {
		"f530c0796b3822cde3bd18677d07b4189de5122dca6109ecbe8cd0e9a6e2f790": {},
	},
	"traffic_search": {
		"5adfaf6a43f0c3d34d3b9d9994394f6dc2e3174d4789600d1b5abe44fa21617c": {},
		"68cd3bfc0d83573b4696a2015b346f60d4950746d08b9658a1f930965d094b95": {},
		"f3561acf3921a6a2742d795d009102872dd02daab3e06df20a0152ae77946e6e": {},
	},
	"update_custom_tool": {
		"f44f48e618598dd2a99e2a2e2cf355da52751dc5f74734616772158c13a9e50c": {},
	},
	"update_finding_report": {
		"243d0fbc8e96f7bb76ac8e1e766baa1fec0c61c458d0689bcc50b5624bdeca9f": {},
		"de8bfe1bf18c7b50faaf8aa4670a4abe75a34f4f52abcf9a8df4aa2961168453": {},
	},
	"update_mcp": {
		"f045b5bd141083f8837c0958af8fdcce92b120a164b407a62d77063926a61f10": {},
	},
	"update_skill_file": {
		"c9c09017e8049d928603dbbfbfc66078d64ef5889368d4f96eb954d86fb6d994": {},
	},
}

// LegacyToolSchemaSHA256 maps a tool key to the set of historical default-schema digests.
var LegacyToolSchemaSHA256 = map[string]map[string]struct{}{
	"add_company_scope": {
		"1148b83ad7f0d240560428331e3e3156be6d632e16c5b4f53ea4db313a491c9f": {},
		"a2576503fca196496fb810873d6eab4a438fc3baba8b403d48d5aca8906304b1": {},
	},
	"add_hint": {
		"81a3edf9b74a68161abf44177d878e074c2cd83029ffe3b481e4237d46e02c45": {},
		"f49166396e96cd320ba77336249e8902242075d939a9f4b3183784537a6ec18a": {},
	},
	"add_intent": {
		"4f1e846d98a2d864aaba60343c43646724370f4a4373ec126cce39315bbb00c0": {},
	},
	"add_task_hint": {
		"641231077c118660c69381f4814f0b234a3bfab59fadd6df2ca4dab16e34747b": {},
		"8f1a0868a563f27a4377168d01e0221ff0536ffee3465979cde902f65b59cec1": {},
	},
	"add_task_scope": {
		"09a12c8dfb78f8e0af39f88345b3e5840289e978d5edeb6bf1c3d5910b52bd4e": {},
		"6148afed45ca873053d7d49426c6dccffc04a0acfc3167783aee231365bdcb57": {},
	},
	"bind_finding_traffic": {
		"c6e20fef4f661a056dbcfae8017faa878acb05afcdc0c6645ab89d921ad0dbb1": {},
	},
	"create_custom_tool": {
		"133e4656acfc4bfcbb2c7af39f1799062b526f526088a07debd88275b5a96f55": {},
	},
	"create_mcp": {
		"0631e656876060ed50845467af8940dff275d5b0b109f55c661d766033d02edd": {},
		"551c72ef5a9fc82e403bc743f66cef056218298f963c2b1c5aecb26a14fa580a": {},
	},
	"create_skill": {
		"79ca2cee65e01d9fe85af95733cf5d1c2801559e76be555b942a37f9d8389360": {},
	},
	"delete_assets_by_host": {
		"c8537929e7f4449cc5cdca4284432c48f953ce14cdfdca5f78f16113972723f6": {},
	},
	"expand_digest": {
		"195e6d23d2c9622e359e62e081990603484f67c25af897686307b8fc21450b2b": {},
		"7ccbb8680abca77b46d38ef17eadac5f63e6967a06ca4edddae75498f2a540cb": {},
	},
	"expand_index": {
		"c76aebaef5272be14cdd48134a96d9a8a92052780c6c0a31921f8d7f8e54b677": {},
	},
	"get_finding_retest_context": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"get_finding_traffic": {
		"1d9e37e5413e4536d3c03093734dbe93b66f73c611991d155ebb4066e1ee12c5": {},
	},
	"get_task_graph": {
		"5ac12509110ede5be63ffacb351c9033692963b4f7fbaec9e010789c2848136a": {},
	},
	"get_task_node_detail": {
		"63e322daf00af66c3bdb4760f0ba0c840e55c37702ae96e8f1bb9f4c180abd3d": {},
	},
	"get_task_worker_trace": {
		"e16e6db15ce1b49fa7f48f246fdf95f00914f3614e8ee608f2d6b6b43dfabca0": {},
	},
	"get_worker_output": {
		"9debd13d7fbd68abb833e90e1255181b18b4e2b4608589eab9e316c24a2d373f": {},
	},
	"get_worker_trace": {
		"28f419a37cd0c0275dced0e1da918de0146a33ac1eed99d63e9f8bf04d274f2c": {},
		"a8e4b3a384fb993a4e93c6a849abfa1530575d539497370fda4590dcc5df4ee4": {},
	},
	"goal_met": {
		"fb8a1cce4d627271fec128df490217763a1789e5db23251b47b416be3373ced5": {},
	},
	"graph_overview": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"insert_assets": {
		"5bda7e6e8d73fdd722ae31dc9aa9204ab8860742e35f7b03ea8d553953aa607d": {},
		"78702c4b9da7b9710b570861ece04d4da6314484b35f69cfff3180d7625a44bb": {},
		"8af3162953a7fecccadaa4591aeada0a7378e365f869977819f7baa49da352a8": {},
		"f39edb92d1d9459952f2b17e902b7cd9d595ab5fd6d4f345db77747496e7502e": {},
	},
	"kill_work": {
		"5b3c16008cf2f3b78d7ba2b858ecfaf0ed3623108f9e7de80a5c284c876eedff": {},
	},
	"list_assets": {
		"0d07b350cb8d4316da5f785715abf7aaf49f4e85f03163888690c654accb3940": {},
		"49780a5a9e31416ad279a5d82e0a091a9d9cb361b17b9afeb33299fa87578e21": {},
	},
	"list_companies": {
		"989193dca6a1b0098cf897b6a0dd1461927981c03a383287c52f2a49cdcd80f4": {},
	},
	"list_facts": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
		"fd95769c695eb8bbd5412720e745503c7412314865f99e6117e441536b194aed": {},
	},
	"list_findings": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"list_goals": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"list_llm_profiles": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"list_task_findings": {
		"5ac12509110ede5be63ffacb351c9033692963b4f7fbaec9e010789c2848136a": {},
	},
	"list_task_worker_traces": {
		"5ac12509110ede5be63ffacb351c9033692963b4f7fbaec9e010789c2848136a": {},
	},
	"list_tasks": {
		"efddc7bd8bbcef73a14eb1ace1ffdaec81e518ef1e13c1e9271d0b8acb694a49": {},
	},
	"list_untested_assets": {
		"0d337d041cbe18f46e5231362d91e22748ac7555b5766748026f3a4fba4dd481": {},
	},
	"list_worker_traces": {
		"1ee9668211dfbb8ce5ada3740e3b26456c531cca4ce700bc08fe82ed4a1469bd": {},
	},
	"node_detail": {
		"485579fda1c67a87fe3c64f5c60a0e6e51b3707cfbf8203081cc439351fbef1d": {},
	},
	"pause_task": {
		"6058a042c6985e7599de7b7da5ed071d10254068396cb577c600be6320567799": {},
	},
	"prove_goal": {
		"ef7eee2ca11acbab5a87f2aa6e8b8e31feb5fde2c077a8bcf16275feaebd5815": {},
	},
	"record_fact": {
		"18152162586d4490c1651838f1811074e847183b99db9d9b49cbe323def55941": {},
	},
	"record_finding_retest_result": {
		"63bbe3d27a96ee382de6d3ec0795e9db0ba76854cf29b025f613aca16bdc97e3": {},
	},
	"report_finding": {
		"0fe5075beb4cffb6daee2f6b5c3ccb974b97eedd1c65446bc2eab3c925ec8407": {},
		"b0d190c0a1dacc7282cb5e501a3ca64912a2908e72f8611a909330df492e29f2": {},
		"d42c8d3a4fe9d72d6868330bb77f5a386c7bc0418a8891e680637b6dc719852c": {},
		"dd1a41acc212a3d059b9b8c22422aab468622f26d970609684cef5f33d00ed80": {},
	},
	"search_all_worker_traces": {
		"4ad19f7a06001c1bb3d1e91de3b37623ed93b7ec52b921875333e40addcea372": {},
	},
	"search_task_worker_traces": {
		"cc02120f5b50d1ad31028428f371591918de54e3764a611fefe4847fa9183827": {},
	},
	"set_constraints": {
		"0f1c225612e984b42c0067642a722cc6ab964bd9aede8eb5286cf4e7fe9109f3": {},
	},
	"set_goals": {
		"a86e4aa2517af52563c767c80ff366b0d38d95f5e8e3a4a9938da6036cf5892e": {},
	},
	"spawn_task": {
		"14fed16767c2ae5ea48ff2eddba338b8d8658ca36a9c45ab8d379baecb6b4f88": {},
		"9c3d471cedb044b3695e47f63469d53a86ba7223b16a89f7d56c49653c2d3152": {},
	},
	"steer_work": {
		"b8af9ecbc011be98992ca412004f36d4d1bcc5963c42f6601f47737096bab6ac": {},
	},
	"traffic_blob": {
		"3ee745920a6633c040f361d55a07504b4eecd05427297072fa28a90f770b8c1d": {},
	},
	"traffic_get": {
		"fe9b7d35c8afb03c9cfe89f02e9be1493c8946ae1d56b95bffa2cea33f1224c9": {},
	},
	"traffic_search": {
		"7f4d72b8c5f4bdd59b3d38c3d93957347dbd23b66d92024c3b868fc1036a37ec": {},
		"9ec292962113f8da8f7c46804d2a1f1f7f30c34817ba2d7b07f30e1cbd0fd3e3": {},
		"b4fc267a72e14b3fd53e235f3ee2786736de51900349fda64c5fab6600839eb3": {},
	},
	"update_custom_tool": {
		"0c9a63c7746da157308dfc71862c2bdb7b855c4348d4d377380f3a48237d3e9a": {},
	},
	"update_finding_report": {
		"0cdf7cf2e4bc901f8734a01a982298f41f16b1f31be3842217525aa608972508": {},
		"dc252a20612d8f528318f15567aaf3b60d19170221ac0ed0d4414f47e9134015": {},
	},
	"update_mcp": {
		"3886ac763c77090161980af5ca0cfb02e500169bea33c06cc40c7587e46343b4": {},
		"d06b7ba1c51d3fc56b2cbd1360cfdd224853e034cd677e2512f9a70a14deba1d": {},
	},
	"update_skill_file": {
		"22bf9272dd59ffa5416a1c6be69b6f5ba512ed7de424f6cee714af209a49d0ae": {},
	},
}
